spring:
  cache:
getnet:
  endpoint: https://api-sandbox.getnet.com.br
  oauth:
    client-id: ----------------------
    client-secret: --------------------------
    seller-id: ----------------------

feign:
  client:
    config:
      default:
        loggerLevel: full

