server:
  port: 8081

getnet:
  endpoint: ${API_URI}
  oauth:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    seller-id: ${SELLER_ID}

feign:
  client:
    config:
      default:
        loggerLevel: full
